/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testgles3_GLUtils */

#ifndef _Included_com_example_testgles3_GLUtils
#define _Included_com_example_testgles3_GLUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testgles3_GLUtils
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_testgles3_GLUtils_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testgles3_GLUtils
 * Method:    getErrors
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testgles3_GLUtils_getErrors
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testgles3_GLUtils
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_testgles3_GLUtils_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_testgles3_GLUtils
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testgles3_GLUtils_display
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testgles3_GLUtils
 * Method:    update
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_com_example_testgles3_GLUtils_update
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     com_example_testgles3_GLUtils
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testgles3_GLUtils_reset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
